version: '3.8'

# networks:
#   frontend:
#     external: true
#   backend:

volumes:
  db:
  
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: demo
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    depends_on:
      - mongo

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:mongo
    
    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongo:
    container_name: mongo
    image: mongo:7.0.12
    restart: always
    volumes:
      - db:/data/db
      - ./mongo:/etc/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    # command: --config /etc/mongo/mongod.conf

  # https://github.com/mongo-express/mongo-express
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: true
    depends_on:
      - mongo
    # network_mode: service:mongo

  # db:
  #   container_name: arena-db
  #   image: postgres:14.3
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data      
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
    # ports:
    #  - 5432:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

# volumes:
  # postgres-data:
